name = "ASDF"
uuid = "686f71d1-807d-59a4-a860-28280ea06d7b"
version = "2.0.0"
authors = ["Erik Schnetter <schnetter@gmail.com>"]

[workspace]
projects = ["test", "docs"]

[deps]
ChunkCodecLibBlosc = "c6a955be-ab7f-4fbb-b38f-caf93db6b928"
ChunkCodecLibBzip2 = "2b723af9-f480-4e8d-a1e4-4a9f5a906122"
ChunkCodecLibLz4 = "7e9cc85e-5614-42a3-ad86-b78f920b38a5"
ChunkCodecLibZlib = "4c0bbee4-addc-4d73-81a0-b6caacae83c8"
ChunkCodecLibZstd = "55437552-ac27-4d47-9aa3-63184e8fd398"
CodecXz = "ba30903b-d9e8-5048-a5ec-d1f5b0d4b47b"
MD5 = "6ac74813-4b46-53a4-afec-0b5dc9d7885c"
PkgVersion = "eebad327-c553-4316-9ea0-9fa01ccd7688"
StridedViews = "4db3bf67-4bd7-4b4e-b153-31dc3fb37143"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
ChunkCodecLibBlosc = "0.2.0"
ChunkCodecLibBzip2 = "0.2.0"
ChunkCodecLibLz4 = "0.2.1"
ChunkCodecLibZlib = "0.2.0"
ChunkCodecLibZstd = "0.2.0"
CodecXz = "0.7.4"
MD5 = "0.2.1"
PkgVersion = "0.3.3"
StridedViews = "0.2.1, 0.3, 0.4"
YAML = "0.4.9"
julia = "1.10"
